# Documentation: http://docs.travis-ci.com/user/languages/python/
language: python
# os:
#   - linux
#   - osx
#   # - windows

python:
  - 3.7.5

notifications:
  email: false

install: 
    - pip3 install --upgrade pip
    - pip3 install pytest pytest-cov tox tox-travis coveralls codecov dill

script: tox

after_success:
    - coveralls
    - codecov
